#!/usr/bin/python2.5

import sys, os
import optparse

usage = 'Usage: %prog [--username=www-data] [--password]'

parser = optparse.OptionParser(usage)
parser.add_option('-u', '--username',
        action='store', dest='username',
        help='set owner\'s working directories username')
parser.add_option('-p', '--password',
        action='store_true', dest='set_password', default=False,
        help='set access password (to stdin)')

if os.environ.has_key('USER'):
    if os.environ['USER'] not in ['root']:
        parser.set_defaults(username=os.environ['USER'])

(options, _) = parser.parse_args(sys.argv[1:])

if not options.username:
    parser.print_help()
    sys.exit(0)


import pwd
from openidserver import localsettings

uid, gid = pwd.getpwnam(options.username)[2:4]

if not os.path.exists(localsettings.ROOT_STORE):
    os.makedirs(localsettings.ROOT_STORE, mode=0750)
os.chown(localsettings.ROOT_STORE, uid, gid)

if not os.path.exists(localsettings.TRUST_ROOT_STORE):
    os.makedirs(localsettings.TRUST_ROOT_STORE, mode=0750)
os.chown(localsettings.TRUST_ROOT_STORE, uid, gid)

if not os.path.exists(localsettings.PASSWORD_STORE):
    os.makedirs(localsettings.PASSWORD_STORE, mode=0750)
os.chown(localsettings.PASSWORD_STORE, uid, gid)


if options.set_password:
    os.setgid(gid)
    os.setuid(uid)

    from openidserver import openidserver
    import getpass

    try:
        if sys.stdin.isatty():
            password = getpass.getpass(u'OpendID server access password: ')
        else:
            password = sys.stdin.readline()
    except KeyboardInterrupt:
        sys.exit(1)

    password = password.decode('utf-8').strip()

    openidserver.password_manager = openidserver.PasswordManager(localsettings.PASSWORD_STORE)
    openidserver.password_manager.set(password)
