#!/usr/bin/python

import sys
import optparse

usage = 'Usage: %prog --username=www-data [--password]'

parser = optparse.OptionParser(usage)
parser.add_option('-u', '--username',
        action='store', dest='username',
        help='set owner\'s working directories username')
parser.add_option('-p', '--password',
        action='store_true', dest='set_password', default=False,
        help='set access password (to stdin)')

(options, _) = parser.parse_args(sys.argv[1:])


if not options.username:
    parser.print_help()
    sys.exit(0)


import os
import pwd

from openidserver import localsettings

uid, gid = pwd.getpwnam(options.username)[2:4]

if not os.path.exists(localsettings.ROOT_STORE):
    os.makedirs(localsettings.ROOT_STORE, mode=0750)
os.chown(localsettings.ROOT_STORE, uid, gid)

if not os.path.exists(localsettings.TRUST_ROOT_STORE):
    os.makedirs(localsettings.TRUST_ROOT_STORE, mode=0750)
os.chown(localsettings.TRUST_ROOT_STORE, uid, gid)

if not os.path.exists(localsettings.PASSWORD_STORE):
    os.makedirs(localsettings.PASSWORD_STORE, mode=0750)
os.chown(localsettings.PASSWORD_STORE, uid, gid)


if options.set_password:
    os.setgid(gid)
    os.setuid(uid)

    from openidserver import openidserver

    password = sys.stdin.readline().strip()
    openidserver.password_manager.set(password)
